FROM confluentinc/confluent-operator:0.1514.1
LABEL org.opencontainers.image.source="internal-image-builder"
LABEL description="CFK operator image mirrored for internal use"
# LABEL workstream="Continuous Streaming Service - KAFMRSC (Kafka multi-region stretched cluster)" \
#       maintainer="Harish" \
#       email="gcpgkekafka@gmail.com" \
#       cmdb_appid="AL12345"